### ISSUE TITLE
Plug in not working with xcode 7.0

### ISSUE THREAD

**Issue by Conrad-m-wise** [contentful/ContentfulXcodePlugin#10]
I can not get the plug in to work in the latest xcode 7 update. I tried removing/re-installing the plugin even tried -> http://pablin.org/2015/05/27/re-enable-alcatraz-on-xcode-6-dot-3-2-or-newer/. But i don't see the plug in in the menu

**Comment by neonichu** [comment]
Sorry, the compatibility UUIDs had to be bumped again — did that now and also released a new binary here: https://github.com/contentful/ContentfulXcodePlugin/releases/tag/0.5
