### ISSUE TITLE
Xcode plug-in menu not showing up in Xcode 7

### ISSUE THREAD

**Issue by Conrad-m-wise** [contentful/ContentfulXcodePlugin#11]
I installed the latest binary and i see Product -> Generate Model from Contentful option in Xcode. But when i click the menu option nothing happens.

**Comment by neonichu** [comment]
Looks like the release ZIP was somehow broken and did not contain the NIB for the "Generate Model" dialog, sorry. I have replaced the latest release with a working one. Thanks for reporting!

**Comment by Conrad-m-wise** [comment]
No problem! Thanks for the quick fixes
